<?php
/**
 * Toit Gallery
 *
 * Provides an image gallery extension for Magento
 *
 * @category	ThinkOverIT
 * @package		Gallery
 * @author		ThinkOverIT
 * @copyright	Copyright (c) 20012, ThinkOverIT.com	
 * @license		http://creativecommons.org/licenses/by-nc-sa/3.0/us/
 * @link		http://www.ThinkOverIT.com
 * @since		Version 0.1.0
 *
 * Please feel free to modify or distribute this as you like,
 * so long as it's for noncommercial purposes and any
 * copies or modifications keep this comment block intact
 *
 * If you would like to use this for commercial purposes,
 * please contact me at info@thinkoverit.com
 *
 * For any feedback, comments, or questions, please post
 * it on our blog at http://www.thinkoverit.com/plugins/magento/gallery/
 *
 */
 
$item = Mage::registry('current_gallery');
$next = $item->getNextItem();
$prev = $item->getPreviousItem();
$nextGalleryId = $next->getGalleryId();
$prevGalleryId = $prev->getGalleryId();
?>
<div class="gallery_container">
	<div class="gallery_photo_wrapper">
<?php if($item->getGalleryId()) { ?>

<?php $thumbnail = $item->getPhotoUrl(); ?>	
			<div class="gallery_item">
				<img src="<?php echo $thumbnail;?>" title="<?php echo $item->getTitle()?>" alt="<?php echo $item->getAlt()?>"/>		           		                

				<div class="gallery_item_caption">
					<span class="gallery_item_title"><a href="<?php echo $this->getGalleryUrl($item)?>"><?php echo $item->getTitle()?></a></span>
					<p class="gallery_item_description"><?php echo $item->getDescription(); ?></p>
				</div>
				<div class="social_wrapper">
					<div class="social_sharing">	
						<div class="share_fb">
							<div class="fb-like" data-href="<?php echo $this->getGalleryUrl($item)?>" 
								data-send="false" data-layout="button_count" data-show-faces="false"></div>
						</div>
						<div class="share_tw">
							<a href="https://twitter.com/share" class="twitter-share-button" data-url<?php echo $this->getGalleryUrl($item)?> 
								data-text="<?php echo htmlspecialchars('Check out "'.$item->getTitle().'"'); ?>">Tweet</a>
						</div>
						<div class="share_gplus">
							<g:plusone size="medium" href<?php echo $this->getGalleryUrl($item)?>"></g:plusone>
						</div>
					</div>
				</div>
		   </div>
<?php if(!empty($prevGalleryId)) { ?>
		   <a class="toit_gallery_prev  <?php echo $this->getFancyClass($prev); ?> " href="<?php echo $this->getGalleryUrl($prev)?>" title="Previous"><span></span></a>
<?php }if(!empty($nextGalleryId)) { ?>
		   <a class="toit_gallery_next  <?php echo $this->getFancyClass($next); ?> " href="<?php echo $this->getGalleryUrl($next)?>" title="Next"><span></span></a>
<?php } ?>
<?php } ?>
		<div class="clear"></div>
	</div>
<script type="text/javascript">

jQuery(document).ready(function() {
<?php if ($this->getRequest()->isXmlHttpRequest()) { ?>
	if (typeof(FB) != 'undefined')
		FB.XFBML.parse($('.gallery_photo_wrapper')[0]);
	if (typeof(gapi) != 'undefined')
		gapi.plusone.go();
	if (typeof(twttr) != 'undefined')
		twttr.widgets.load();

<?php } else { ?>

	var twscript = '<script type="text/javascript">';
		twscript += '/*<![CDATA[*/';
		twscript += '!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");';
		twscript += '/*/]]>*/';
		twscript += '<\/script>';
	var gplusscript = '<script type="text/javascript">';
		gplusscript += '/*<![CDATA[*/';
		gplusscript += '(function() {';
		gplusscript += 'var po = document.createElement(\'script\'); po.type = \'text/javascript\'; po.async = true;';
		gplusscript += 'po.src = \'https://apis.google.com/js/plusone.js\';';
		gplusscript += 'var s = document.getElementsByTagName(\'script\')[0]; s.parentNode.insertBefore(po, s);';
		gplusscript += '}());';
		gplusscript += '/*/]]>*/';
		gplusscript += '<\/script>';
	var fbscript = '<script type="text/javascript">';
		fbscript += '/*<![CDATA[*/';
		fbscript += '(function(d, s, id) {';
		fbscript += 'var js, fjs = d.getElementsByTagName(s)[0];';
		fbscript += 'if (d.getElementById(id)) {return;}';
		fbscript += 'if (d.getElementById(id)) {return;}';
		fbscript += 'js = d.createElement(s); js.id = id;';
		fbscript += 'js.src = "//connect.facebook.net/en_GB/all.js#xfbml=1";';
		fbscript += 'fjs.parentNode.insertBefore(js, fjs);}';
		fbscript += '(document, "script", "facebook-jssdk"));';
		fbscript += '/*/]]>*/';
		fbscript += '<\/script>';

	if (typeof(FB) == 'undefined')
		jQuery('body').append(fbscript);
	if (typeof(gapi) == 'undefined')
		jQuery('body').append(gplusscript);
	if (typeof(twttr) == 'undefined')
		jQuery('body').append(twscript);
<?php } ?>
});	
	jQuery(".gallery_fancybox").fancybox({type: 'ajax',autoSize : true,});

</script>
</div>